### ISSUE TITLE
Module name question

### ISSUE THREAD

**Issue by o3o** [p0nce/binrange#4]
Hi, 
I 've seen that you've changed the your module name to `package.d`

But [package](http://wiki.dlang.org/DIP37) is  standard name that provides a way to import a package.
Maybe old name is better...what do you think?

**Comment by p0nce** [comment]
Explain why it would be better.
It does'nt change the user code.

```
import binrange;
```

**Comment by o3o** [comment]
Hi Guillaume
It's not so important, just a convention.

First, from http://dlang.org/module.html: 

> Modules have a one-to-one correspondence with source files. The module name is, by default, the file name with the path and extension stripped off, and can be set explicitly with the module declaration.

and from http://ddili.org/ders/d.en/modules.html

> By default, the name of a module is the same as its filename without the .d extension. 

Then , our case `module binrange;` => file `binrange.d`

Second, `package.d` is a conventional module name for importing all modules in a package. 

from http://ddili.org/ders/d.en/modules.html

> ... It is achieved by a special configuration file in the package directory, which must always be named as package.d.

and from http://dlang.org/module.html#package-module

> A package module can be used to publicly import other modules, while enabling a simpler import syntax..... The package module must have the file name package.d. 

Thank for your attention.

**Comment by p0nce** [comment]
Indeed it didn't make much sense, I've renamed it.

Use the v1.0.2+ tag

**Comment by o3o** [comment]
Hi Guillaume,
Why in your opinion `package.` convention does not make sense?
It's very common:
- https://github.com/Hackerpilot/Dscanner/blob/master/src/analysis/package.d
- https://github.com/Abscissa/SDLang-D/blob/master/src/sdlang/package.d
- https://github.com/nomad-software/etcetera/blob/master/source/etcetera/collection/package.d

which convention do you use ?

BAT

**Comment by p0nce** [comment]
Of course it makes sense, I was talking about the previous naming.
package.d is not only a convention, the compiler recognize it.

**Comment by o3o** [comment]
Ops...my English is really poor :)

Thank again, specially for your d-idioms... it's awesome

BAT

**Comment by p0nce** [comment]
Thanks:) np
